import api from "./trekanicApi"
import { socket, EVENT_APPOINTMENTS_FREE, EVENT_APPOINTMENTS_FREED, EVENT_APPOINTMENTS_STORE, EVENT_APPOINTMENTS_STORED, ROUTE_APPOINTMENTS, EVENT_APPOINTMENTS_ALL, emitAppointment } from "./socket"

export { api, socket, EVENT_APPOINTMENTS_FREE, EVENT_APPOINTMENTS_FREED, EVENT_APPOINTMENTS_STORE, EVENT_APPOINTMENTS_STORED, ROUTE_APPOINTMENTS, EVENT_APPOINTMENTS_ALL, emitAppointment }
